// <auto-generated />
using System;
using Examen_2M1_is_.DAta;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen_2M1_is_.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20240703152857_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Examen_2M1_is_.Habitaciones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("EstadoDeHabitacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumDeHabitacion")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoDeHabitacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("Examen_2M1_is_.Reservas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("FechaDeFIn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("Habitacioneid")
                        .HasColumnType("int");

                    b.Property<string>("estadoDeReserva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("habitacionId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Habitacioneid");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Examen_2M1_is_.Reservas", b =>
                {
                    b.HasOne("Examen_2M1_is_.Habitaciones", "Habitacione")
                        .WithMany("Reservas")
                        .HasForeignKey("Habitacioneid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacione");
                });

            modelBuilder.Entity("Examen_2M1_is_.Habitaciones", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
